### PR TITLE
Dev fix service leak fixes #553

### LINKED ISSUE #553: Starting/Stopping Orbot Rapidly will Cause Service Connection to Leak
```
  android.app.ServiceConnectionLeaked: Service org.torproject.android.service.OrbotService has leaked ServiceConnection org.torproject.android.service.OrbotService$1@376a954 that was originally bound here
        at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1841)
        at android.app.LoadedApk.getServiceDispatcherCommon(LoadedApk.java:1699)
        at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:1685)
        at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1817)
        at android.app.ContextImpl.bindService(ContextImpl.java:1757)
        at android.content.ContextWrapper.bindService(ContextWrapper.java:762)
        at org.torproject.android.service.OrbotService.startTorService(OrbotService.java:855)
        at org.torproject.android.service.OrbotService.startTor(OrbotService.java:703)
        at org.torproject.android.service.OrbotService.-$$Nest$mstartTor(Unknown Source:0)
        at org.torproject.android.service.OrbotService$IncomingIntentRouter.run(OrbotService.java:1428)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
```
After this exception the next time you try to start tor the app will crash ...

### PR DESCRIPTION
**Pull request by n8fr8**
This may fix the service connection leak issue.

### CODE REVIEW

**Comment by n8fr8** [comment]
trace output: https://gist.github.com/n8fr8/f1c30e8cce10a8cb65f734af7deca6f8

**Comment by bitmold** [comment]
This looks good to me, though I'm unable to reproduce the lock issue on my device ..

File: app/src/main/java/org/torproject/android/OrbotMainActivity.java [hunk 1]
```diff
@@ -817,105 +829,98 @@ private synchronized void updateStatus(String torServiceMsg, String newTorStatus
...
-        }
-
-        if (torStatus == null) {
-            return;
-        }
-
-        switch (torStatus) {
-            case TorServiceConstants.STATUS_ON:
+        if (!TextUtils.isEmpty(newTorStatus)) {
+            if (torStatus == null || (newTorStatus != null && newTorStatus.equals(torStatus))) {
```
Comment (bitmold) [inline app/src/main/java/org/torproject/android/OrbotMainActivity.java:833]: inconsequential, but `newTorStatus` should never be null there because `TextUtils.isEmpty` returned false

**Review by bitmold — APPROVED** [review]
lgtm

**Comment by syphyr** [comment]
The latest commits in this PR fix the Orbot shutdown issues I was having with https://github.com/guardianproject/tor-android/pull/65 
Thanks!
